version: '3.9'

services:
  nginx:
      build:
        context: ./src/nginx
      ports:
        - "8080:80"
      volumes:
        - .:/app
      depends_on:
        - wordpress
      networks:
        - cloud_1_network
  cloud_db:
    context: ./src/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_cloud:/var/lib/mysql
    networks:
      - cloud-1-network
volumes:
  db_cloud:
networks:
  cloud_1_network:
    driver: bridge
