version: '3.9'

services:
  wordpress:
    container_name: wordpress_container
    env_file:
      - .env
    build:
      context: ./services/wordpress
    ports:
      - "9000:9000"
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - mysql
      # mysql:
        # condition: service_healthy
    restart: always
    networks:
      - cloud_1_network
  nginx:
      build:
        context: ./services/nginx
      ports:
        - "443:443"
      volumes:
        - wp_volume:/var/www/html
      depends_on:
        - wordpress
      networks:
        - cloud_1_network
      restart: always
  mysql:
    container_name: mysql
    build:
      context: ./services/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ./services/mysql/db_volume:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
    restart: on-failure
    networks:
      - cloud_1_network

  phpmyadmin:
      container_name: phpmyadmin_container
      image: phpmyadmin
      environment:
        # PMA_ARBITRARY: 1
        PMA_HOST: mysql
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      restart: always
      depends_on:
        - mysql
      ports:
        - "8080:80"
      # volumes:
      #   - ./services/phpmyadmin/apache2.conf:/etc/apache2/conf-available/servername.conf
      # command: >
      #   sh -c "ln -s /etc/apache2/conf-available/servername.conf /etc/apache2/conf-enabled/servername.conf &&
      #         apache2-foreground"
      networks:
        - cloud_1_network

volumes:
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      device: /home/abouazi/data/wp
      type: none
      o: bind

  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      device: /home/abouazi/data/db
      type: none
      o: bind

networks:
  cloud_1_network:
    driver: bridge
    attachable: true
