version: '3.9'

services:
  # nginx:
  #     build:
  #       context: ./src/nginx
  #     ports:
  #       - "8080:80"
  #     volumes:
  #       - .:/app
  #     depends_on:
  #       - wordpress
  #     networks:
  #       - cloud_1_network
  mysql:
    context: ./src/mysql
    container_name: db_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - mysql_network
volumes:
  db_volume:
networks:
  mysql_network:
    driver: bridge
