version: '3.9'

services:
  nginx:
      build:
        context: ./requirements/nginx
      ports:
        - "3030:80"
      volumes:
        - .:/app
      # depends_on:
      #   - wordpress
      networks:
        - cloud_1_network
  mysql:
    container_name: db_container
    # image: mysql:5.7
    build:
      context: ./requirements/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./requirements/mysql/setup.sh:/setup.sh
      - db_volume:/var/lib/mysql
    restart: always
    networks:
      - mysql_network

  phpmyadmin:
      container_name: phpmyadmin_container
      image: phpmyadmin
      environment:
        # PMA_ARBITRARY: 1
        PMA_HOST: db_container
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      restart: always
      depends_on:
        - mysql
      ports:
        - "8080:80"
      networks:
        - mysql_network

volumes:
  db_volume:
    name: db_volume
networks:
  cloud_1_network:
    name: cloud_1_network
    driver: bridge
    attachable: true
  mysql_network:
    name: mysql_network
    driver: bridge
    attachable: true
