- name: install necessary packages
  hosts: servers
  become: true
  tasks:
    - name: install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ca-certificates
        - curl
    - name: update apt
      apt:
        update_cache: yes
    - name: install docker and docker-compose
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - docker-compose